# Generate base tests:::
# for s in 2.10.4 2.9.3; do
#   for t in `ls -d scalding-*`; do
# echo "    - scala: $s"
# echo "      env: BUILD=\"base\" TEST_TARGET=\"$t\""
# echo "      script: \"scripts/run_test.sh\""
# echo ""
# done
# done
language: scala
jdk: oraclejdk7
sudo: false
before_install: umask 0022
script:
  - "echo no op"
matrix:
  include:
#BASE TESTS
    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-args"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-avro"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-commons"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-core"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-date"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-hadoop-test"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-hraven"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-jdbc"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-json"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-parquet"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-parquet-scrooge"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="base" TEST_TARGET="scalding-repl"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-args"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-avro"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-commons"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-core"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-date"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-hadoop-test"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-hraven"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-jdbc"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-json"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-parquet"
      script: "scripts/run_test.sh"

    - scala: 2.9.3
      env: BUILD="base" TEST_TARGET="scalding-repl"
      script: "scripts/run_test.sh"

    - scala: 2.10.4
      env: BUILD="test tutorials"
      script:
      - "scripts/build_assembly_no_test.sh scalding"
      - "scripts/test_tutorials.sh"
    - scala: 2.10.4
      env: BUILD="test matrix tutorials"
      script:
      - "scripts/build_assembly_no_test.sh scalding"
      - "scripts/test_matrix_tutorials.sh"
    - scala: 2.10.4
      env: BUILD="test repl tutorials"
      script:
      - "scripts/build_assembly_no_test.sh scalding-repl"
      - "scripts/test_repl_tutorial.sh"
    - scala: 2.10.4
      env: BUILD="test typed tutorials"
      script:
      - "scripts/build_assembly_no_test.sh scalding-core"
      - "scripts/test_typed_tutorials.sh"
    - scala: 2.9.3
      env: BUILD="test tutorials"
      script:
      - "scripts/build_assembly_no_test.sh scalding"
      - "scripts/test_tutorials.sh"
    - scala: 2.9.3
      env: BUILD="test matrix tutorials"
      script:
      - "scripts/build_assembly_no_test.sh scalding"
      - "scripts/test_matrix_tutorials.sh"
    - scala: 2.9.3
      env: BUILD="test repl tutorials"
      script:
      - "scripts/build_assembly_no_test.sh scalding-repl"
      - "scripts/test_repl_tutorial.sh"
    - scala: 2.9.3
      env: BUILD="test typed tutorials"
      script:
      - "scripts/build_assembly_no_test.sh scalding-core"
      - "scripts/test_typed_tutorials.sh"

notifications:
  irc: "chat.freenode.net#scalding"

